"""The overview panel's whole data model: one unit, six fields.

Five of the six are computed from the AST and one — `name` — is generated by a
model. That split is the feature's central claim (spec §2, research §12.4), and
it is load-bearing rather than incidental: the interface renders the generated
field differently from the computed ones so a wrong name is a correctable
annoyance rather than a reason to distrust the panel.

Nothing here is ever written to the `.ipynb`.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..notebook_document.models import NotebookDomainError

#: The four `state` values, in precedence order — a block can be more than one
#: of these at once, and this is which one it reports.
#:
#: Run-state before risk is deliberate. "You never ran this" and "you ran this
#: out of order" are facts about *this notebook's* history and are what a reader
#: is navigating by; "this cell touches the network" is a property of the code
#: that the execution confirmation already surfaces at the moment it matters.
#: Showing risk in a navigation panel instead of an unrun block would trade a
#: fact the panel is uniquely placed to give for one it merely duplicates.
BLOCK_STATES = ("never-run", "out-of-order", "risky", "ok")


@dataclass(frozen=True)
class Def:
    """A function defined in a block, and every cell that references it.

    `call_sites` counts *name references*, not `ast.Call` nodes. A callback
    handed to `solve_ivp(rhs, ...)` is used, and a Call-only scan reported every
    one of them dead (research §13.3). An empty tuple therefore means genuinely
    unused, and the panel renders it as such.
    """

    name: str
    call_sites: tuple[int, ...] = ()


@dataclass(frozen=True)
class Block:
    """A contiguous run of cells: one generated field, five computed ones."""

    start: int
    end: int
    name: str
    state: str = "ok"
    produces: tuple[str, ...] = ()
    defines: tuple[Def, ...] = ()
    marks: tuple[str, ...] = ()


@dataclass(frozen=True)
class Overview:
    """What `GET /overview` answers with.

    `generated` distinguishes the two ways the panel can be non-empty: a model
    pass that produced these boundaries and names, or the deterministic fallback
    (spec §6), whose names are absent and whose boundaries are — measured —
    degraded rather than merely terser. The panel has to say which it is showing.
    """

    blocks: tuple[Block, ...]
    generated: bool
    stale: bool
    cell_count: int = 0
    #: Why the last generation attempt failed, if one did. Surfaced verbatim so
    #: "generation failed" is never the whole story the user gets.
    error: str | None = None


class OverviewError(NotebookDomainError):
    code = "overview_failed"
    message = "Notebook overview could not be generated"
    status_code = 502


class SegmentationRejected(OverviewError):
    """The model answered, and the answer was not a valid partition.

    Separate from a transport failure because it is the case spec §4.3 makes
    non-negotiable: the response is discarded rather than rendered, and the
    reasons travel with the error so the panel can say what was wrong.
    """

    code = "overview_segmentation_rejected"
    message = "Model response was not a valid partition of the notebook"

    def __init__(self, problems: list[str]) -> None:
        self.problems = list(problems)
        super().__init__("; ".join(problems) or self.message, problems=self.problems)


class NotebookTooLarge(OverviewError):
    """The prompt would exceed what a single pass can carry (spec §10.2).

    Chunking is explicitly undefined above roughly 500 cells, so this refuses
    rather than silently segmenting a prefix and presenting it as the whole map.
    """

    code = "overview_notebook_too_large"
    message = "Notebook is too large to segment in one pass"
    status_code = 413

    def __init__(self, cell_count: int, limit: int) -> None:
        super().__init__(
            f"This notebook has {cell_count} cells; the overview can segment "
            f"about {limit} in one pass.",
            cellCount=cell_count, limit=limit,
        )
