#!/usr/bin/env python3
"""Regenerate `constraints/ci.txt` from a clean resolve of `.[test]`.

CI installs under this file so that an upstream release cannot turn `main` red
on a pull request whose diff could not have caused it (#59). That protection is
only worth having if bumping it is a single obvious command, because a lockfile
which is a chore to update becomes a lockfile people route around.

Resolves into a throwaway virtualenv rather than reading the current one: a
development environment accumulates things CI never installs (playwright, build
backends, whatever was needed once), and every one of them would be pinned here
for no reason.

Run it with the Python version CI uses -- resolution is version-dependent, and
a file generated on a newer interpreter can name versions that have no wheel
for CI's. The script refuses to run on a different minor rather than let that
happen quietly.

    python3.12 scripts/update_constraints.py

The resolve happens on whatever platform you run it from, which is usually not
CI's Linux. That is safe by construction -- a constraints file only caps
versions of packages that are installed, so a macOS-only entry is ignored on
Linux -- and anything it does get wrong fails immediately on the pull request
that changes this file, which is the whole point.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
import venv
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONSTRAINTS = REPO / "constraints" / "ci.txt"
WORKFLOW = REPO / ".github" / "workflows" / "ci.yml"

# The interpreter CI sets up. Read from the workflow rather than repeated here,
# so bumping CI's Python does not silently leave this script pinning the old one.
_PYTHON_VERSION = re.compile(r'python-version:\s*"([\d.]+)"')

HEADER = '''\
# What CI resolves, pinned so an upstream release cannot turn `main` red on
# somebody's unrelated pull request (#59).
#
# On 2026-08-24 `mcp 2.1.0` was uploaded at 19:04:29Z, CI picked it up on the
# next run because `pyproject.toml` asks for `mcp>=2,<3`, and three tests
# started failing on a branch whose diff could not have caused it. That looked
# exactly like a flake, was filed as one (#54), and cost a week.
#
# This is a *constraints* file, not a requirements file: it caps versions of
# packages that get installed and never causes one to be installed. So entries
# that do not apply to CI's platform are simply ignored, and `pyproject.toml`
# keeps its permissive ranges -- the published wheel is unaffected, and users
# are not stranded on the SDK we happened to test against.
#
# A dependency change now arrives as a deliberate edit to this file, with its
# own diff and its own author. Drift is still discovered, by the weekly
# unpinned run in `.github/workflows/dependency-drift.yml` and by the `wheel`
# job, which stays unpinned on purpose -- see the comments there.
#
# Generated by scripts/update_constraints.py on Python {version}. Do not
# hand-edit; run the script instead.
'''


def ci_python_version() -> str:
    """The minor CI sets up, e.g. "3.12"."""
    found = _PYTHON_VERSION.findall(WORKFLOW.read_text())
    if not found:
        sys.exit(f"no python-version found in {WORKFLOW}")
    if len(set(found)) != 1:
        sys.exit(f"{WORKFLOW} sets up more than one Python: {sorted(set(found))}")
    return found[0]


def resolve(into: Path) -> str:
    """`pip freeze` of a fresh venv with `.[test]` and nothing else."""
    venv.EnvBuilder(with_pip=True, clear=True).create(into)
    python = into / "bin" / "python"
    for command in (
        [str(python), "-m", "pip", "install", "--quiet", "--upgrade", "pip"],
        [str(python), "-m", "pip", "install", "--quiet", "-e", f"{REPO}[test]"],
    ):
        subprocess.run(command, check=True)
    frozen = subprocess.run(
        [str(python), "-m", "pip", "freeze", "--exclude-editable"],
        check=True, capture_output=True, text=True,
    )
    return frozen.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="fail if the file is out of date instead of rewriting it",
    )
    arguments = parser.parse_args()

    wanted = ci_python_version()
    running = f"{sys.version_info.major}.{sys.version_info.minor}"
    if running != wanted:
        sys.exit(
            f"CI runs Python {wanted} and this is {running}. Resolution is "
            f"version-dependent, so a file written here would pin versions CI "
            f"cannot install. Re-run with python{wanted}."
        )

    with tempfile.TemporaryDirectory(prefix="constraints-") as directory:
        frozen = resolve(Path(directory) / "venv")
    rendered = HEADER.format(version=wanted) + frozen

    if arguments.check:
        if CONSTRAINTS.read_text() != rendered:
            print(
                f"{CONSTRAINTS.relative_to(REPO)} is out of date. "
                f"Run: python{wanted} scripts/update_constraints.py",
                file=sys.stderr,
            )
            return 1
        print(f"{CONSTRAINTS.relative_to(REPO)} is up to date.")
        return 0

    CONSTRAINTS.parent.mkdir(exist_ok=True)
    CONSTRAINTS.write_text(rendered)
    print(f"wrote {CONSTRAINTS.relative_to(REPO)} ({frozen.count(chr(10))} pins)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
