// Re-fetch the webfonts the tab uses and write them into the bundle.
//
// The tab used to link fonts.googleapis.com. That made a local-only editor —
// loopback binding, a scoped agent, a backend that owns every mutation — reach
// out to a third party on every load, and left every icon rendering as its own
// ligature name for anyone offline or behind a blocked CDN (#51). The fonts
// live in `frontend/src/assets/fonts/` now and `frontend/src/fonts.css` points
// at them, so the built bundle has no external origin at all.
//
// Run this when a font changes, and — the case that actually comes up — when a
// new icon is added. Material Symbols is subsetted to the icon names this app
// uses, so an icon nobody vendored is a blank box:
//
//   node scripts/vendor-fonts.mjs
//
// Forgetting is caught: `frontend/src/fonts.test.ts` fails when the app uses an
// icon this has not vendored, `backend/tests/test_bundle_external_origins.py`
// fails if a CDN link comes back, and `e2e/offline.spec.ts` runs the tab with
// every other origin refused. All three exist because none of this can be
// noticed by hand — it looks correct to anyone with a network.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

import { ROOT, SRC, FONTS_CSS as CSS_OUT, iconNames } from "./icon-names.mjs";

const FONT_DIR = path.join(SRC, "assets", "fonts");

// Google serves woff2 only to a browser-ish UA; with curl's default it answers
// with ttf, which is three times the size for the same glyphs.
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const TEXT_CSS = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap";
const ICON_CSS = (names) =>
  `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,400,0..1,0&icon_names=${names.join(",")}&display=block`;

async function get(url, binary = false) {
  const response = await fetch(url, { headers: { "User-Agent": UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return binary ? Buffer.from(await response.arrayBuffer()) : response.text();
}

// Rewrite one Google stylesheet so every src points at a file beside this
// bundle, downloading each as we go. Weights of a variable family share a
// file, so the same URL is fetched once and referenced by all of them.
async function localise(css, nameFor, downloaded) {
  const blocks = [...css.matchAll(/(?:\/\* (\S+) \*\/\s*)?@font-face \{(.*?)\}/gs)];
  const out = [];
  for (const [, subset, body] of blocks) {
    const family = /font-family: '([^']+)'/.exec(body)[1];
    const url = /url\((\S+?)\)/.exec(body)[1];
    let file = downloaded.get(url);
    if (!file) {
      file = nameFor(family, subset);
      const bytes = await get(url, true);
      await writeFile(path.join(FONT_DIR, file), bytes);
      downloaded.set(url, file);
      console.log(`  ${file.padEnd(36)} ${bytes.length.toLocaleString().padStart(8)} bytes`);
    }
    out.push(body.trim().replace(/url\(\S+?\)/, `url("./assets/fonts/${file}")`).replace(/\n\s*/g, "\n  "));
  }
  return out;
}

const icons = await iconNames();
console.log(`${icons.length} icons: ${icons.join(", ")}\n`);
await mkdir(FONT_DIR, { recursive: true });

const downloaded = new Map();
const text = await localise(await get(TEXT_CSS), (family, subset) => `${family.toLowerCase().replace(/ /g, "-")}-${subset}.woff2`, downloaded);
const symbols = await localise(await get(ICON_CSS(icons)), () => "material-symbols-outlined.woff2", downloaded);

const header = `/* Generated by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * The three families the tab uses, served from the bundle rather than from
 * Google, so a local-only editor makes no external request and its icons
 * survive an offline or CDN-blocked host (#51).
 *
 * Inter and JetBrains Mono are SIL OFL 1.1; Material Symbols is Apache 2.0.
 * See assets/fonts/README.md.
 *
 * Material Symbols is subsetted to exactly the ${icons.length} icons the app renders,
 * which is why it is ${(await readFile(path.join(FONT_DIR, "material-symbols-outlined.woff2"))).length.toLocaleString()} bytes rather than the full font's ~400 KB —
 * and why adding an <Icon> means re-running the script. The icons, so a diff
 * of this file says which one arrived:
 *
${icons.map((n) => ` *   ${n}`).join("\n")}
 *
 * Each text family keeps Google's per-script split and its unicode-range, so
 * the browser still downloads only the subsets a notebook's characters need.
 */`;

await writeFile(CSS_OUT, `${header}\n\n${[...text, ...symbols].map((b) => `@font-face {\n  ${b}\n}`).join("\n\n")}\n`);
console.log(`\nwrote ${path.relative(ROOT, CSS_OUT)}`);
